pipeline {
    agent any
    tools{
        maven 'maven'
    }
    stages {
        stage('Checkout') {
            steps {
                // Checkout your source code from version control system (e.g., Git)
                git branch: 'master', url: 'https://github.com/manojsaik/devops-proj.git'
            }
        }
        
        stage('Build') {
            steps {
                // Use Maven to build your project
                sh 'mvn clean package'
            }
        }

        
        stage('Deploy'){
            steps{
                deploy adapters: [tomcat9(credentialsId: '848fde89-fcb9-4f42-9647-573b6c0008e8', path: '', url: 'http://3.145.55.34:8080')], contextPath: null, war: 'webapp/target/webapp.war'
            }
            
        }
    }
}

