pipeline {
    agent any
    tools{
        maven 'maven'
    }
    stages {
        stage('Checkout') {
            steps {
                // Checkout your source code from version control system (e.g., Git)
                git branch: 'master', url: 'https://github.com/manojsaik/devops-proj.git'
            }
        }
        
        stage('Build') {
            steps {
                // Use Maven to build your project
                sh 'mvn clean package'
            }
        }

        
        stage('Deploy'){
            steps{
                deploy adapters: [tomcat9(credentialsId: 'tmc-deployer', path: '', url: 'http://3.144.13.133:8080')], contextPath: null, war: 'webapp/target/webapp.war'
            }
            
        }
    }
}

